CREATE TABLE gift_certificate (
                                  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                  name VARCHAR(255) NOT NULL,
                                  description VARCHAR(255) NOT NULL,
                                  price DECIMAL(10,2) NOT NULL,
                                  duration INTEGER NOT NULL,
                                  create_date TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
                                  last_update_date TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE tag (
                     id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                     name VARCHAR(250)
);

CREATE TABLE gift_certificate_tag (
                                      certificate_id INTEGER REFERENCES gift_certificate(id),
                                      tag_id INTEGER REFERENCES tag(id),
                                      PRIMARY KEY (certificate_id, tag_id)
);